services:

  service-registry:
    image: urmaliya2003/service-registry:latest
    ports:
      - "8761:8761"

  config-server:
    image: urmaliya2003/config-server:latest
    ports:
      - "8888:8888"
    depends_on:
      - service-registry

  user-service:
    image: urmaliya2003/user-service:latest
    ports:
      - "9001:9001"
    depends_on:
      - service-registry
      - config-server

  flight-service:
    image: urmaliya2003/flight-service:latest
    ports:
      - "9002:9002"
    depends_on:
      - service-registry
      - config-server

  booking-service:
    image: urmaliya2003/booking-service:latest
    ports:
      - "9003:9003"
    depends_on:
      - service-registry
      - config-server

  report-service:
    image: urmaliya2003/report-service:latest
    ports:
      - "9004:9004"
    depends_on:
      - service-registry
      - config-server

  api-gateway:
    image: urmaliya2003/api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - config-server

  frontend:
    image: urmaliya2003/frontend-service:latest
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway