version: '3.8'

services:

  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - service-registry

  user-service:
    build: ./user-service
    ports:
      - "9001:9001"
    depends_on:
      - service-registry
      - config-server

  flight-service:
    build: ./flight-service
    ports:
      - "9002:9002"
    depends_on:
      - service-registry
      - config-server

  booking-service:
    build: ./booking-service
    ports:
      - "9003:9003"
    depends_on:
      - service-registry
      - config-server

  report-service:
    build: ./report-service
    ports:
      - "9004:9004"
    depends_on:
      - service-registry
      - config-server

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - config-server

  frontend:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway