spring.application.name=report-service

server.port=9004

#Register to Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
#Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Enable tracing
management.tracing.sampling.probability=1.0

# Zipkin server URL
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans